import { ThemeContextProvider } from '@/context/ThemeContext';
import './globals.css';
import type { Metadata } from 'next';
import { Sidebar } from './components/layout/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true}>
        <ThemeContextProvider>
          <div className='flex'>
            <Sidebar.Root>
              <div>
                <Sidebar.Container />
                <Sidebar.Footer />
              </div>
            </Sidebar.Root>
            {children}
          </div>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
